---

- name: Download Plesk license file
  get_url: url={{plesk_license_url}} dest=/root/plsk-license.xml mode=0644
  when: plesk_license_url is defined
  ignore_errors: true

- name: Install Plesk License from File
  command: plesk bin license --install /root/plsk-license.xml
  when: plesk_license_url is defined
  ignore_errors: true

- name: Install Plesk License via Activation code
  command: plesk bin license --install {{plesk_license_activation_code}}
  when: plesk_license_activation_code is defined
  ignore_errors: true

- name: Initialize Plesk
  shell: (plesk bin init_conf --check-configured || plesk bin init_conf --init -passwd {{plesk_admin_password}} -admin_info_not_required true -ip-type shared -license_agreed true -admin_info_not_required true -email test@plesk.ru -company Plesk -address Nsk -city Nsk -state Nsk -zip 630000 -country RU -phone 89139130000)

- name: Set Admin password
  shell: plesk bin admin --set-password -passwd "{{plesk_admin_password}}"
  when: plesk_admin_password is defined